version: '3.9'

services:
  telegram_bot:
    build:
      context: ./TelegramBot
      dockerfile: Dockerfile
    container_name: telegram_bot
    ports:
      - "3000:3000"
    command: sh -c "python main.py"
    networks:
      - default

